# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ghchen/Desktop/lab6/lab6.cache/wt [current_project]
set_property parent.project_path C:/Users/ghchen/Desktop/lab6/lab6.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/ghchen/Desktop/lab6/lab6.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/ghchen/Desktop/lab6/lab6.srcs/sources_1/imports/Desktop/fux4to1.v
  C:/Users/ghchen/Desktop/lab6/lab6.srcs/sources_1/imports/Desktop/countUD4L.v
  C:/Users/ghchen/Desktop/lab6/lab6.srcs/sources_1/imports/Desktop/fux8to1.v
  C:/Users/ghchen/Desktop/lab6/lab6.srcs/sources_1/imports/Desktop/edgeD.v
  C:/Users/ghchen/Desktop/lab6/lab6.srcs/sources_1/new/TIMEBITCH.v
  C:/Users/ghchen/Desktop/lab6/lab6.srcs/sources_1/imports/Desktop/lab6_clks.v
  C:/Users/ghchen/Desktop/lab6/lab6.srcs/sources_1/imports/Desktop/selector.v
  C:/Users/ghchen/Desktop/lab6/lab6.srcs/sources_1/new/fuckingsteak.v
  C:/Users/ghchen/Desktop/lab6/lab6.srcs/sources_1/new/score.v
  C:/Users/ghchen/Desktop/lab6/lab6.srcs/sources_1/imports/Desktop/ringcounter.v
  C:/Users/ghchen/Desktop/lab6/lab6.srcs/sources_1/new/countTIME.v
  C:/Users/ghchen/Desktop/lab6/lab6.srcs/sources_1/imports/Desktop/hex7seg.v
  C:/Users/ghchen/Desktop/lab6/lab6.srcs/sources_1/new/topdawg.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ghchen/Desktop/lab6/lab6.srcs/constrs_1/imports/Desktop/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/ghchen/Desktop/lab6/lab6.srcs/constrs_1/imports/Desktop/Basys3_Master.xdc]


synth_design -top topdawg -part xc7a35tcpg236-1


write_checkpoint -force -noxdef topdawg.dcp

catch { report_utilization -file topdawg_utilization_synth.rpt -pb topdawg_utilization_synth.pb }
