# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ghchen/Desktop/lab3/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/ghchen/Desktop/lab3/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/ghchen/Desktop/lab3/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/ghchen/Desktop/lab3/project_1.srcs/sources_1/imports/sources_1/new/fux4to1.v
  C:/Users/ghchen/Desktop/lab3/project_1.srcs/sources_1/imports/sources_1/new/fux8to1.v
  C:/Users/ghchen/Desktop/lab3/project_1.srcs/sources_1/imports/sources_1/new/fullsend.v
  C:/Users/ghchen/Desktop/lab3/project_1.srcs/sources_1/imports/sources_1/imports/Downloads/lab3_digsel.v
  C:/Users/ghchen/Desktop/lab3/project_1.srcs/sources_1/imports/sources_1/new/hex7seg.v
  C:/Users/ghchen/Desktop/lab3/project_1.srcs/sources_1/imports/sources_1/new/BusFux.v
  C:/Users/ghchen/Desktop/lab3/project_1.srcs/sources_1/imports/sources_1/new/AddSub8.v
  C:/Users/ghchen/Desktop/lab3/project_1.srcs/sources_1/imports/sources_1/new/TopGun.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ghchen/Desktop/lab3/project_1.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/ghchen/Desktop/lab3/project_1.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc]


synth_design -top TopGun -part xc7a35tcpg236-1


write_checkpoint -force -noxdef TopGun.dcp

catch { report_utilization -file TopGun_utilization_synth.rpt -pb TopGun_utilization_synth.pb }
