# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ghchen/Desktop/lab4/lab4.cache/wt [current_project]
set_property parent.project_path C:/Users/ghchen/Desktop/lab4/lab4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/ghchen/Desktop/lab4/lab4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/ghchen/Desktop/lab4/lab4.srcs/sources_1/new/fux4to1.v
  C:/Users/ghchen/Desktop/lab4/lab4.srcs/sources_1/new/countUD3L.v
  C:/Users/ghchen/Desktop/lab4/lab4.srcs/sources_1/new/countUD5L.v
  C:/Users/ghchen/Desktop/lab4/lab4.srcs/sources_1/new/fux8to1.v
  C:/Users/ghchen/Desktop/lab4/lab4.srcs/sources_1/new/ringcounter.v
  C:/Users/ghchen/Desktop/lab4/lab4.srcs/sources_1/new/selector.v
  C:/Users/ghchen/Desktop/lab4/lab4.srcs/sources_1/new/lab4_clks.v
  C:/Users/ghchen/Desktop/lab4/lab4.srcs/sources_1/new/hex7seg.v
  C:/Users/ghchen/Desktop/lab4/lab4.srcs/sources_1/new/edgeD.v
  C:/Users/ghchen/Desktop/lab4/lab4.srcs/sources_1/new/counterUD16L.v
  C:/Users/ghchen/Desktop/lab4/lab4.srcs/sources_1/new/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ghchen/Desktop/lab4/lab4.srcs/constrs_1/imports/ass/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/ghchen/Desktop/lab4/lab4.srcs/constrs_1/imports/ass/Basys3_Master.xdc]


synth_design -top top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
