# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ghchen/Desktop/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/ghchen/Desktop/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/ghchen/Desktop/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/ghchen/Desktop/project_1/project_1.srcs/sources_1/imports/New folder/fux4to1.v}
  C:/Users/ghchen/Desktop/project_1/project_1.srcs/sources_1/imports/Desktop/countUD5L.v
  {C:/Users/ghchen/Desktop/project_1/project_1.srcs/sources_1/imports/New folder/fux8to1.v}
  C:/Users/ghchen/Desktop/project_1/project_1.srcs/sources_1/new/diezbit.v
  C:/Users/ghchen/Desktop/project_1/project_1.srcs/sources_1/new/russia.v
  {C:/Users/ghchen/Desktop/project_1/project_1.srcs/sources_1/imports/New folder/selector.v}
  {C:/Users/ghchen/Desktop/project_1/project_1.srcs/sources_1/imports/New folder/ringcounter.v}
  {C:/Users/ghchen/Desktop/project_1/project_1.srcs/sources_1/imports/New folder/hex7seg.v}
  C:/Users/ghchen/Desktop/project_1/project_1.srcs/sources_1/new/playa.v
  C:/Users/ghchen/Desktop/project_1/project_1.srcs/sources_1/imports/Desktop/edgeD.v
  C:/Users/ghchen/Desktop/project_1/project_1.srcs/sources_1/new/steakmachine.v
  C:/Users/ghchen/Desktop/project_1/project_1.srcs/sources_1/new/drawline.v
  C:/Users/ghchen/Desktop/project_1/project_1.srcs/sources_1/new/fuckingtimer.v
  C:/Users/ghchen/Desktop/project_1/project_1.srcs/sources_1/new/playerbitch.v
  C:/Users/ghchen/Desktop/project_1/project_1.srcs/sources_1/new/timeshit.v
  C:/Users/ghchen/Desktop/project_1/project_1.srcs/sources_1/new/sync.v
  C:/Users/ghchen/Desktop/project_1/project_1.srcs/sources_1/imports/Desktop/lab7_clks.v
  C:/Users/ghchen/Desktop/project_1/project_1.srcs/sources_1/new/border.v
  C:/Users/ghchen/Desktop/project_1/project_1.srcs/sources_1/new/dickplay.v
  C:/Users/ghchen/Desktop/project_1/project_1.srcs/sources_1/new/topoffmydick.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ghchen/Desktop/project_1/project_1.srcs/constrs_1/imports/Desktop/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/ghchen/Desktop/project_1/project_1.srcs/constrs_1/imports/Desktop/Basys3_Master.xdc]


synth_design -top topoffmydick -part xc7a35tcpg236-1


write_checkpoint -force -noxdef topoffmydick.dcp

catch { report_utilization -file topoffmydick_utilization_synth.rpt -pb topoffmydick_utilization_synth.pb }
