webtalk_init -webtalk_dir C:/Users/ghchen/Desktop/lab4/lab4.sim/sim_1/behav/xsim.dir/testTC_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu May 03 13:15:14 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1682563" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0ce0a12057c05e7c911d650b845f998e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5c0075c219a7425dacc8e7e2cc963c8e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM)2 Duo CPU     E8500  @ 3.16GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3159 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "29" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "714 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "67 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "2643" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "1429" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "256" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "3.77_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "151016_KB" -context "xsim\\usage"
webtalk_transmit -clientid 99214712 -regid "" -xml C:/Users/ghchen/Desktop/lab4/lab4.sim/sim_1/behav/xsim.dir/testTC_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/ghchen/Desktop/lab4/lab4.sim/sim_1/behav/xsim.dir/testTC_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/ghchen/Desktop/lab4/lab4.sim/sim_1/behav/xsim.dir/testTC_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
